[package]
name = "db_utils"
version = "0.1.0"
authors = ["yn <642410979@qq.com>"]
edition = "2021"
description = "有关mysql的集成简化工具"
license = "GPL-3.0"
readme = "README.md"

[[bin]]
name = "db_tool"
path = "db_tool/main.rs"

[workspace]
members = [
    "system_config",
    "macro_builder",
    "system_db",
]
